//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Blog.Models
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class blogsContainer : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“blogsContainer”部分中的连接字符串初始化新 blogsContainer 对象。
        /// </summary>
        public blogsContainer() : base("name=blogsContainer", "blogsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 blogsContainer 对象。
        /// </summary>
        public blogsContainer(string connectionString) : base(connectionString, "blogsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 blogsContainer 对象。
        /// </summary>
        public blogsContainer(EntityConnection connection) : base(connection, "blogsContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BlogSample> BlogSample
        {
            get
            {
                if ((_BlogSample == null))
                {
                    _BlogSample = base.CreateObjectSet<BlogSample>("BlogSample");
                }
                return _BlogSample;
            }
        }
        private ObjectSet<BlogSample> _BlogSample;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 BlogSample EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBlogSample(BlogSample blogSample)
        {
            base.AddObject("BlogSample", blogSample);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="blogs", Name="BlogSample")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BlogSample : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 BlogSample 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static BlogSample CreateBlogSample(global::System.String id)
        {
            BlogSample blogSample = new BlogSample();
            blogSample.Id = id;
            return blogSample;
        }

        #endregion

        #region 简单属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, false, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Notice
        {
            get
            {
                return _Notice;
            }
            set
            {
                OnNoticeChanging(value);
                ReportPropertyChanging("Notice");
                _Notice = StructuralObject.SetValidValue(value, true, "Notice");
                ReportPropertyChanged("Notice");
                OnNoticeChanged();
            }
        }
        private global::System.String _Notice;
        partial void OnNoticeChanging(global::System.String value);
        partial void OnNoticeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Author
        {
            get
            {
                return _Author;
            }
            set
            {
                OnAuthorChanging(value);
                ReportPropertyChanging("Author");
                _Author = StructuralObject.SetValidValue(value, true, "Author");
                ReportPropertyChanged("Author");
                OnAuthorChanged();
            }
        }
        private global::System.String _Author;
        partial void OnAuthorChanging(global::System.String value);
        partial void OnAuthorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Brows
        {
            get
            {
                return _Brows;
            }
            set
            {
                OnBrowsChanging(value);
                ReportPropertyChanging("Brows");
                _Brows = StructuralObject.SetValidValue(value, "Brows");
                ReportPropertyChanged("Brows");
                OnBrowsChanged();
            }
        }
        private Nullable<global::System.Int32> _Brows;
        partial void OnBrowsChanging(Nullable<global::System.Int32> value);
        partial void OnBrowsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Recommend
        {
            get
            {
                return _Recommend;
            }
            set
            {
                OnRecommendChanging(value);
                ReportPropertyChanging("Recommend");
                _Recommend = StructuralObject.SetValidValue(value, "Recommend");
                ReportPropertyChanged("Recommend");
                OnRecommendChanged();
            }
        }
        private Nullable<global::System.Int32> _Recommend;
        partial void OnRecommendChanging(Nullable<global::System.Int32> value);
        partial void OnRecommendChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Addr
        {
            get
            {
                return _Addr;
            }
            set
            {
                OnAddrChanging(value);
                ReportPropertyChanging("Addr");
                _Addr = StructuralObject.SetValidValue(value, true, "Addr");
                ReportPropertyChanged("Addr");
                OnAddrChanged();
            }
        }
        private global::System.String _Addr;
        partial void OnAddrChanging(global::System.String value);
        partial void OnAddrChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CreateTime
        {
            get
            {
                return _CreateTime;
            }
            set
            {
                OnCreateTimeChanging(value);
                ReportPropertyChanging("CreateTime");
                _CreateTime = StructuralObject.SetValidValue(value, "CreateTime");
                ReportPropertyChanged("CreateTime");
                OnCreateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _CreateTime;
        partial void OnCreateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnCreateTimeChanged();

        #endregion

    }

    #endregion

}
